### PR TITLE
fix bug when using custom User model

### PR DESCRIPTION
**Pull request by damms005**
When using a custom User model and logged in, author cannot view blogs using the public-facing url because the post author's `belongsTo()` relationship will be referencing the wrong `User` model.

This PR fixes this bug

### CODE REVIEW

**Comment by damms005** [comment]
@WebDevEtc the StyleCI is having issues with files I did not even touch. Am I PRing against the wrong branch?

**Comment by samberrry** [comment]
@damms005 any bug fix is done on this package: https://github.com/vhessam/laravel-blogger

**Comment by WebDevEtc** [comment]
Hi, thanks for the PR @damms005. I will include it in the next release (on this repo...)

**Comment by WebDevEtc** [comment]
Due to merge conflicts (I moved some files around since this PR) I will just make this change manually (not via this PR) but thanks for contributing! 
I'll link to this PR in the commit.

**Pull request closed without merging**
